spring:
  config:
    import: ${CONFIG_IMPORT_URL:configserver:http://localhost:8070}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:localhost:8070}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_URL:localhost:9094}
  h2:
    console.enabled: true
  datasource:
    url: jdbc:postgresql://${USER_MGM_POSTGRESQL_URL:localhost}:5432/${USER_MGM_POSTGRES_DB:postgres}
    username: ${USER_MGM_POSTGRES_USER:postgres}
    password: ${USER_MGM_POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.web: ERROR
    com.eca.usermgmt: DEBUG
    org.hibernate: ERROR
    org.springframework.orm.jpa: INFO
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
app:
  kafka:
    enabled: true
  topic:
    name: ${USER_MGM_TOPIC:user_mgmt_to_notification}
    partitions: ${KAFKA_PARTITIONS:1}
    replica-factor: ${REPLICA_FACTOR:1}
  application:
    cache:
      expiryInSec: 10800
