spring:
  cloud:
    inetutils:
      preferredNetworks: ${EUREKA_PREFERRED_NETWORKS:198.168}
  application:
    name: ecausermgmt
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 6090

eureka:
  instance:
    preferIpAddress: ${EUREKA_PREFER_IP:false}
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: ["beans", "metrics","health","heapdump","info","liquibase"]
        exclude: "env,beans"

logging:
  level:
    root: INFO
app:
  secret:
    key: ${JWT_SECRET_KEY:Vfj69nm&^%3KjinRvFVSKJSJKJKhjsd87812jkJKJKLAAJK}
  jwt:
    expirationTime: ${JWT_EXPIRATION_TIME:1734431739}
  cache:
    enabled: true
    expiryTimeoutInMinutes: ${CACHE_EXPIRY_TIMEOUT:60}
  pool:
    maxIdle: ${POOL_MAX_IDLE:15}
    maxTotal: ${POOL_MAX_TOTAL:25}
    minIdle: ${POOL_MIN_IDLE:10}
  redis:
    host: ${REDIS_HOSTNAME:192.168.117.129}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    connectTimeOutInSeconds: 120
  openapi:
    dev-url: http://localhost:${server.port}
    prod-url: https://eca-api.com

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

catalog-service:
  baseUrl: ${CATALOG_SERVICE_URL:http://localhost:8080}